### PR TITLE
Made internal linking CSS to external linking CSS

### PR DESCRIPTION
**Pull request by Sanath91009**

### CODE REVIEW

**Comment by ArchismanKarmakar** [comment]
fix the background. the background had the GIF but its not working now. fix it. except that rest are fine

**Comment by Sanath91009** [comment]
But its working fine for me ...

**Comment by ArchismanKarmakar** [comment]
> But its working fine for me ... Once can you confirm

you have used: `background-image: url(img/img4.gif);`
but the CSS file is unable to get img as img is in root folder so change it to `background-image: url(../../img/img4.gif);`
I thing you have used LiveServer but you haven't tested by directly running the `index.html`
fix this thing in every page, and update the fork and pr I'll assign you in the next project

**Comment by Sanath91009** [comment]
Sorry I havent considered that because live server is not showing any error . Now I have updated . I hope there will be no mistake now . Once can you review so that I can work on another issue
Thanks

**Comment by ArchismanKarmakar** [comment]
> Sorry I haven't considered that because live server is not showing any error . Now I have updated . I hope there will be no mistake now . Once can you review so that I can work on another issue Thanks

great job!

**Pull request merged**
