### PR TITLE
Added redirecting functionality  to index.html on clicking login and Signup

### LINKED ISSUE #52: BUG: Clicking Login/Signup should immediately switch to the login/signup page of the React App; as per sitemap.
###  Also delete the login/signup html as the react app is there**

SITEAMP

### PR DESCRIPTION
**Pull request by ShivaRapolu01**
## Issue
Fixes #52 

## Description
Added redirecting functionality  to index.html on clicking login and Signup

## Type of change
You can write manually also

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Screenshot
[Screenshot of the fix if required.](https://www.awesomescreenshot.com/video/6588378?key=8be627dfa2e6a0f091ab6f0c66da7ed7)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ShivaRapolu01** [comment]
A special thanks to @shmiitg  for helping to come out from chaos

**Comment by ArchismanKarmakar** [comment]
> A special thanks to @shmiitg bhaiya for helping to come out from chaos

sorry i was checking it out now, but i suddenly saw this. i was very busy today @ShivaRapolu01  bhaiya , please pardon me for being late. @ShivaRapolu01 @shmiitg i am giving points to both of you bhaiya. Both of you are senior to me. thank you

**Comment by ShivaRapolu01** [comment]
@ArchismanKarmakar no problem brother , only a small change was to be made but I took it upto creating another file

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar no problem brother , only a small change was to be made but I took it upto creating another file

there is a small bug @ShivaRapolu01 bhaiya please fix that , the url should be https://localhost...... but there is http & it is not working.

**Pull request merged**
